######################################################################
# Automatically generated by qmake (3.1) Tue May 6 23:08:38 2025
######################################################################

TEMPLATE = app
TARGET = uart_comm
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += build/config/sdkconfig.h build/bootloader/config/sdkconfig.h
SOURCES += build/project_elf_src_esp32.c \
           main/main.c \
           build/bootloader/project_elf_src_esp32.c \
           build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/bootloader/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           build/bootloader/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/esp-idf/mbedtls/mbedtls/library/error.c \
           build/esp-idf/mbedtls/mbedtls/library/psa_crypto_driver_wrappers_no_static.c \
           build/esp-idf/mbedtls/mbedtls/library/ssl_debug_helpers_generated.c \
           build/esp-idf/mbedtls/mbedtls/library/version_features.c
